version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "2248:5432"
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U your_username -d your_database" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./app
    ports:
      - "2247:8000"
    depends_on:
      postgres:
        condition: service_healthy
